-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE UNLOGGED TABLE IF NOT EXISTS public.cnae
(
    cod_cnae character varying(7) COLLATE pg_catalog."default" NOT NULL,
    nome_cnae character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cnae_pkey PRIMARY KEY (cod_cnae)
);

CREATE UNLOGGED TABLE IF NOT EXISTS public.empresa
(
    cnpj_basico character varying(8) COLLATE pg_catalog."default" NOT NULL,
    razao_social character varying(200) COLLATE pg_catalog."default",
    cod_natureza_juridica character varying(4) COLLATE pg_catalog."default" NOT NULL,
    cod_qualificacao_responsavel character varying(2) COLLATE pg_catalog."default" NOT NULL,
    capital_social numeric(16, 2) NOT NULL,
    cod_porte character varying(2) COLLATE pg_catalog."default",
    ente_federativo_responsavel character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT empresa_pkey PRIMARY KEY (cnpj_basico)
);

CREATE UNLOGGED TABLE IF NOT EXISTS public.estabelecimento
(
    cnpj_basico character varying(8) COLLATE pg_catalog."default" NOT NULL,
    cnpj_ordem character varying(4) COLLATE pg_catalog."default" NOT NULL,
    cnpj_dv character varying(2) COLLATE pg_catalog."default" NOT NULL,
    matriz_filial character varying(1) COLLATE pg_catalog."default" NOT NULL,
    nome_fantasia character varying(60) COLLATE pg_catalog."default",
    cod_situacao_cadastral character varying(2) COLLATE pg_catalog."default" NOT NULL,
    data_situacao_cadastral date,
    cod_motivo_situacao_cadastral character varying(2) COLLATE pg_catalog."default" NOT NULL,
    nome_cidade_exterior character varying(60) COLLATE pg_catalog."default",
    cod_pais character varying(3) COLLATE pg_catalog."default",
    data_inicio_atividade date NOT NULL,
    cod_cnae_principal character varying(7) COLLATE pg_catalog."default" NOT NULL,
    cod_cnae_secundario text COLLATE pg_catalog."default",
    tipo_logradouro character varying(20) COLLATE pg_catalog."default",
    logradouro character varying(60) COLLATE pg_catalog."default",
    numero character varying(6) COLLATE pg_catalog."default",
    complemento character varying(200) COLLATE pg_catalog."default",
    bairro character varying(60) COLLATE pg_catalog."default",
    cep character varying(8) COLLATE pg_catalog."default",
    uf character varying(2) COLLATE pg_catalog."default" NOT NULL,
    cod_municipio character varying(4) COLLATE pg_catalog."default",
    ddd_telefone_1 character varying(4) COLLATE pg_catalog."default",
    telefone_1 character varying(10) COLLATE pg_catalog."default",
    ddd_telefone_2 character varying(4) COLLATE pg_catalog."default",
    telefone_2 character varying(10) COLLATE pg_catalog."default",
    ddd_fax character varying(4) COLLATE pg_catalog."default",
    fax character varying(10) COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    situacao_especial character varying(100) COLLATE pg_catalog."default",
    data_situacao_especial date,
    CONSTRAINT estabelecimento_pkey PRIMARY KEY (cnpj_basico, cnpj_ordem, cnpj_dv)
);

CREATE UNLOGGED TABLE IF NOT EXISTS public.estabelecimento_cnae_sec
(
    cnpj_basico character varying(8) COLLATE pg_catalog."default" NOT NULL,
    cnpj_ordem character varying(4) COLLATE pg_catalog."default" NOT NULL,
    cnpj_dv character varying(2) COLLATE pg_catalog."default" NOT NULL,
    cod_cnae character varying(7) COLLATE pg_catalog."default" NOT NULL
);

CREATE UNLOGGED TABLE IF NOT EXISTS public.motivo
(
    cod_motivo character varying(2) COLLATE pg_catalog."default" NOT NULL,
    nome_motivo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT motivo_pkey PRIMARY KEY (cod_motivo)
);

CREATE UNLOGGED TABLE IF NOT EXISTS public.municipio
(
    cod_municipio character varying(4) COLLATE pg_catalog."default" NOT NULL,
    nome_municipio character varying(60) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT municipio_pkey PRIMARY KEY (cod_municipio)
);

CREATE UNLOGGED TABLE IF NOT EXISTS public.natureza_juridica
(
    cod_natureza character varying(4) COLLATE pg_catalog."default" NOT NULL,
    nome_natureza character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT natureza_juridica_pkey PRIMARY KEY (cod_natureza)
);

CREATE UNLOGGED TABLE IF NOT EXISTS public.pais
(
    cod_pais character varying(3) COLLATE pg_catalog."default" NOT NULL,
    nome_pais character varying(60) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pais_pkey PRIMARY KEY (cod_pais)
);

CREATE UNLOGGED TABLE IF NOT EXISTS public.qualificacao_socio
(
    cod_qualificacao character varying(2) COLLATE pg_catalog."default" NOT NULL,
    nome_qualificacao character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT qualificacao_socio_pkey PRIMARY KEY (cod_qualificacao)
);

CREATE UNLOGGED TABLE IF NOT EXISTS public.simples
(
    cnpj_basico character varying(8) COLLATE pg_catalog."default",
    opcao_simples character varying(1) COLLATE pg_catalog."default",
    data_opcao_simples date,
    data_exclusao_simples date,
    opcao_mei character varying(1) COLLATE pg_catalog."default",
    data_opcao_mei date,
    data_exclusao_mei date
);

CREATE UNLOGGED TABLE IF NOT EXISTS public.socio
(
    cnpj_basico character varying(8) COLLATE pg_catalog."default" NOT NULL,
    identificador_socio character varying(1) COLLATE pg_catalog."default" NOT NULL,
    nome_socio character varying(200) COLLATE pg_catalog."default",
    cnpj_cpf_socio character varying(14) COLLATE pg_catalog."default",
    cod_qualificacao_socio character varying(2) COLLATE pg_catalog."default" NOT NULL,
    data_entrada_sociedade date NOT NULL,
    cod_pais character varying(3) COLLATE pg_catalog."default",
    cpf_representante_legal character varying(11) COLLATE pg_catalog."default",
    nome_representante_legal character varying(100) COLLATE pg_catalog."default",
    cod_qualificacao_representante_legal character varying(2) COLLATE pg_catalog."default",
    cod_faixa_etaria character varying(1) COLLATE pg_catalog."default" NOT NULL
);

ALTER TABLE IF EXISTS public.empresa
    ADD CONSTRAINT fk_empresa_1 FOREIGN KEY (cod_natureza_juridica)
    REFERENCES public.natureza_juridica (cod_natureza) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_empresa_natureza
    ON public.empresa(cod_natureza_juridica);


ALTER TABLE IF EXISTS public.empresa
    ADD CONSTRAINT fk_empresa_2 FOREIGN KEY (cod_qualificacao_responsavel)
    REFERENCES public.qualificacao_socio (cod_qualificacao) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estabelecimento
    ADD CONSTRAINT fk_estabelecimento_1 FOREIGN KEY (cnpj_basico)
    REFERENCES public.empresa (cnpj_basico) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_estab_empresa
    ON public.estabelecimento(cnpj_basico);


ALTER TABLE IF EXISTS public.estabelecimento
    ADD CONSTRAINT fk_estabelecimento_2 FOREIGN KEY (cod_cnae_principal)
    REFERENCES public.cnae (cod_cnae) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_estab_cnae_principal
    ON public.estabelecimento(cod_cnae_principal);


ALTER TABLE IF EXISTS public.estabelecimento
    ADD CONSTRAINT fk_estabelecimento_3 FOREIGN KEY (cod_municipio)
    REFERENCES public.municipio (cod_municipio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_estab_municipio
    ON public.estabelecimento(cod_municipio);


ALTER TABLE IF EXISTS public.estabelecimento
    ADD CONSTRAINT fk_estabelecimento_4 FOREIGN KEY (cod_pais)
    REFERENCES public.pais (cod_pais) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estabelecimento
    ADD CONSTRAINT fk_estabelecimento_5 FOREIGN KEY (cod_motivo_situacao_cadastral)
    REFERENCES public.motivo (cod_motivo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estabelecimento_cnae_sec
    ADD CONSTRAINT fk_estabelecimento_cnae_sec_1 FOREIGN KEY (cnpj_basico, cnpj_ordem, cnpj_dv)
    REFERENCES public.estabelecimento (cnpj_basico, cnpj_ordem, cnpj_dv) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_cnae_sec_estab
    ON public.estabelecimento_cnae_sec(cnpj_basico, cnpj_ordem, cnpj_dv);


ALTER TABLE IF EXISTS public.estabelecimento_cnae_sec
    ADD CONSTRAINT fk_estabelecimento_cnae_sec_2 FOREIGN KEY (cod_cnae)
    REFERENCES public.cnae (cod_cnae) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.simples
    ADD CONSTRAINT fk_simples_1 FOREIGN KEY (cnpj_basico)
    REFERENCES public.empresa (cnpj_basico) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_simples_empresa
    ON public.simples(cnpj_basico);


ALTER TABLE IF EXISTS public.socio
    ADD CONSTRAINT fk_socio_1 FOREIGN KEY (cnpj_basico)
    REFERENCES public.empresa (cnpj_basico) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_socio_empresa
    ON public.socio(cnpj_basico);


ALTER TABLE IF EXISTS public.socio
    ADD CONSTRAINT fk_socio_2 FOREIGN KEY (cod_pais)
    REFERENCES public.pais (cod_pais) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.socio
    ADD CONSTRAINT fk_socio_3 FOREIGN KEY (cod_qualificacao_socio)
    REFERENCES public.qualificacao_socio (cod_qualificacao) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.socio
    ADD CONSTRAINT fk_socio_4 FOREIGN KEY (cod_qualificacao_representante_legal)
    REFERENCES public.qualificacao_socio (cod_qualificacao) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;